//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Slide item</summary>
	[PublishedContentModel("slideItem")]
	public partial class SlideItem : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SlideItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// slideImage
		///</summary>
		[ImplementPropertyType("slideImage")]
		public IPublishedContent SlideImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("slideImage"); }
		}

		///<summary>
		/// Slide title
		///</summary>
		[ImplementPropertyType("slideTitle")]
		public string SlideTitle
		{
			get { return this.GetPropertyValue<string>("slideTitle"); }
		}

		///<summary>
		/// Slide url
		///</summary>
		[ImplementPropertyType("slideUrl")]
		public string SlideUrl
		{
			get { return this.GetPropertyValue<string>("slideUrl"); }
		}
	}
}
